config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  root "messages#index"

  get "/messages/:id", to: "messages#show", as: :message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :stash_user_id

  def index
  end

  def show
  end

  private

  def stash_user_id
    cookies.signed[:user_id] = current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChannelTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div style="margin-top: 10px;">
  [<%= message.user.email %>] <%= message.body %>
</div>

app/views/messages/index.html.erb
<h2>Messaging Test</h2>

<div>
  Logged in as: <%= current_user.email %>
</div>
<br>

Check out these rooms:
<br>
<%= link_to "Games", message_path("games") %>
<br>
<%= link_to "Programming", message_path("programming") %>

app/views/messages/show.html.erb
<input id="message"></input>
<button id="submit">Send</button>

<div id="messages" data-id="<%= params[:id] %>">
  <h4>Messages:</h4>
  <%= render Message.where(room_id: params[:id]) %>
</div>